### ISSUE TITLE
Foreach error PHP7

### ISSUE THREAD

**Issue by alex-seedcms** [getgrav/grav-plugin-custom-css#2]
This plugins doesn't work in PHP7 due to the foreach code changes in 7.

**Comment by flaviocopes** [comment]
I tested with both PHP 5.6 and 7.0 and I have no problems, do you have any error or simply the CSS file is not added?

**Comment by alex-seedcms** [comment]
Ya the file isn't added so it could be that too. I thought it was the foreach. Screenshot attached.
![ss-grav](https://cloud.githubusercontent.com/assets/12736992/17109526/2618d7bc-524d-11e6-90b7-a073bc6f8c3f.jpg)

**Comment by flaviocopes** [comment]
What's in your `user/config/plugins/custom-css.yaml` file? Mine for example is

```
enabled: true
css_inline: 'body { color: blue }'
path: xxxxxxx
css_files:
  -
    path: /user/my_css/TEST.css
    priority: 0
  -
    path: /user/my_css/TEST2.css
    priority: 0
```
