### ISSUE TITLE
Wrapper for highlighting css / less / sass / scss

### ISSUE THREAD

**Issue by fourroses666** [getgrav/grav-plugin-custom-css#6]
Nice plugin, for development I really like this plugin.
To make it even better I'd like to use a "wrapper" so the inline css has highlighting.
When looking at the files me as rookie really don't know how to add it. 
I have just started to work with Grav.

I think this is a good highlighter:
http://prismjs.com/index.html

It looks like all you need to do is adding a css and js file and the textarea needs a class.

```<pre><code class="language-css"><textarea...```

```
<link href="themes/prism.css" rel="stylesheet" />
<script src="prism.js"></script>
```

Example here: https://jsfiddle.net/gnev4yd1/

**Comment by fourroses666** [comment]
Ok so it seems its already available. Now it only needs to work :)
When changing the blueprint.yaml nothing happens unfortunately.

```
css_inline:      
      type: editor
      label: Inline-CSS
      codemirror:
        mode: 'gfm'
        indentUnit: 4
        autofocus: true
        indentWithTabs: false
        lineNumbers: true
        styleActiveLine: true
        gutters: ['CodeMirror-lint-markers']
        lint: true
```
